// Lista padronizada de bairros/localidades para geração de rotas.
// Fontes municipais:
// - Cuiabá: mapa oficial de abairramento.
// - Várzea Grande: relação oficial de bairros, distritos, loteamentos e residenciais por região.
window.BAIRROS_POR_CIDADE = Object.freeze({
    "Cuiabá": Object.freeze([
        "Altos do Coxipó",
        "Alvorada",
        "Barra do Pari",
        "Bela Marina",
        "Bela Vista",
        "Boa Esperança",
        "Bosque da Saúde",
        "Cachoeira das Garças",
        "Campo Velho",
        "Campo Verde",
        "Canjica",
        "Carumbé",
        "Centro Político",
        "Centro-Norte",
        "Centro-Sul",
        "Cidade Alta",
        "Cidade Verde",
        "Cohab São Gonçalo",
        "Coophamil",
        "Coophema",
        "Coxipó",
        "Da Goiabeira",
        "Da Lixeira",
        "Despraiado",
        "Do Areão",
        "Do Baú",
        "Do Poção",
        "Do Porto",
        "Do Quilombo",
        "Do Terceiro",
        "Dom Aquino",
        "Dom Bosco",
        "Dos Araés",
        "Dos Bandeirantes",
        "Duque de Caxias",
        "Grande Terceiro",
        "Jardim Aclimação",
        "Jardim Califórnia",
        "Jardim Comodoro",
        "Jardim Cuiabá",
        "Jardim das Américas",
        "Jardim das Palmeiras",
        "Jardim dos Ipês",
        "Jardim Eldorado",
        "Jardim Europa",
        "Jardim Florianópolis",
        "Jardim Fortaleza",
        "Jardim Gramado",
        "Jardim Imperial",
        "Jardim Industriário",
        "Jardim Itália",
        "Jardim Leblon",
        "Jardim Mariana",
        "Jardim Mossoró",
        "Jardim Passaredo",
        "Jardim Paulista",
        "Jardim Petrópolis",
        "Jardim Presidente",
        "Jardim Santa Isabel",
        "Jardim Shangri-Lá",
        "Jardim Tropical",
        "Jardim Ubirajara",
        "Jardim Universitário",
        "Jardim Vitória",
        "Jordão",
        "Lagoa Azul",
        "Morada da Serra",
        "Morada do Ouro",
        "Morada dos Nobres",
        "Nossa Senhora Aparecida",
        "Nova Conquista",
        "Nova Esperança",
        "Novo Colorado",
        "Novo Horizonte",
        "Novo Mato Grosso",
        "Novo Terceiro",
        "Osmar Cabral",
        "Paiaguás",
        "Paraíso",
        "Parque Atalaia",
        "Parque Cuiabá",
        "Parque Georgia",
        "Parque Ohara",
        "Pascoal Ramos",
        "Pedra 90",
        "Pedregal",
        "Pico do Amor",
        "Planalto",
        "Popular",
        "Praeirinho",
        "Praeiro",
        "Primeiro de Março",
        "Recanto dos Pássaros",
        "Residencial Coxipó",
        "Residencial Itamarati",
        "Residencial Santa Inês",
        "Residencial São Carlos",
        "Ribeirão da Ponte",
        "Ribeirão do Lipa",
        "Santa Cruz",
        "Santa Laura",
        "Santa Marta",
        "Santa Rosa",
        "São Francisco",
        "São Gonçalo Beira Rio",
        "São João Del Rei",
        "São José",
        "São Roque",
        "São Sebastião",
        "Sol Nascente",
        "Terra Nova",
        "Tijucal",
        "Três Barras",
        "UFMT (Campus Universitário)",
        "Vista Alegre",
    ]),
    "Várzea Grande": Object.freeze([
        "13 de Setembro",
        "15 de Maio",
        "23 de Setembro",
        "24 de Dezembro",
        "7 de Maio",
        "8 de Março",
        "Adriana",
        "Água Limpa",
        "Água Vermelha",
        "Alameda",
        "Alberto Canelas",
        "Alice Gonçalves de Campos",
        "Alto da Boa Vista",
        "Altos da Boa Vista",
        "Amarílio",
        "Ana Luiza",
        "Ana Vitória",
        "Asa Bela",
        "Asa Branca",
        "Athaíde Ferreira",
        "Athaíde Monteiro",
        "Aurília Sales Curvo",
        "Bela Vista I",
        "Bela Vista II",
        "Boa Vista",
        "Bonsucesso",
        "Brasil Novo",
        "Buenos Aires",
        "Cabo Michel",
        "Canelas",
        "Capão do Pequi",
        "Capão Grande",
        "Capela do Piçarrão",
        "Carrapicho",
        "Cassyra Lúcia",
        "Centro",
        "Centro Empresarial de Várzea Grande",
        "Centro Esportivo",
        "Centro Norte",
        "Centro Sul",
        "Cerrados",
        "Chácara Estância São Carlos",
        "Chapéu do Sol",
        "Cidade de Deus",
        "Cidade Jardim",
        "Cidade Nova Hollywood",
        "Colinas Verdejantes",
        "Construmat",
        "Costa Verde",
        "Cristina",
        "Cristo Rei",
        "Cruzeiro do Sul",
        "Dage",
        "Dep. Nilton Figueiredo",
        "Distrito Industrial",
        "Dom Bosco",
        "Dom Orlando Chaves",
        "Domingos Sávio",
        "Don Diego",
        "Dorcelina Folador",
        "Eldorado (parte)",
        "Eliane Gomes",
        "Elias Domingos",
        "Embauval",
        "Engordador",
        "Esmeralda",
        "Espinheiro",
        "Esplanada",
        "Estância São Carlos",
        "Estrela Dalva",
        "Fazendinha",
        "Ferraz",
        "Figueirinha",
        "Formigueiro",
        "Frutal de Minas",
        "Glória",
        "Gonçalo Botelho",
        "Governador José Fragelli",
        "Hélio Ponce de Arruda",
        "Ikaray",
        "Industrial I",
        "Industrial II",
        "Industrial III",
        "Industrial IV",
        "Jaime Campos",
        "Jardim Acácia",
        "Jardim Adália",
        "Jardim Aeroporto",
        "Jardim Alá",
        "Jardim América",
        "Jardim Andaraí",
        "Jardim Aroeira",
        "Jardim Beira Rio",
        "Jardim Botafogo",
        "Jardim Buenos Aires",
        "Jardim Califórnia",
        "Jardim Campinas",
        "Jardim Campo Verde",
        "Jardim Corsário",
        "Jardim Costa Verde",
        "Jardim das Acácias",
        "Jardim das Canoas",
        "Jardim das Flores",
        "Jardim das Oliveiras",
        "Jardim das Palmeiras",
        "Jardim dos Estados",
        "Jardim dos Girassóis",
        "Jardim dos Pássaros",
        "Jardim Eldorado",
        "Jardim Glória",
        "Jardim Guanabara",
        "Jardim Ikaray",
        "Jardim Imperador",
        "Jardim Imperador II",
        "Jardim Ipanema",
        "Jardim Itororó",
        "Jardim Kataguás",
        "Jardim Manaíra",
        "Jardim Marajoara I",
        "Jardim Marajoara II",
        "Jardim Mariana",
        "Jardim Maringá I",
        "Jardim Maringá I Ampliação",
        "Jardim Maringá II",
        "Jardim Maringá III",
        "Jardim Nova Kanaã",
        "Jardim Novo Horizonte",
        "Jardim Novo Niterói",
        "Jardim Ouro Verde",
        "Jardim Panorama",
        "Jardim Paula I",
        "Jardim Paula I (2ª Etapa)",
        "Jardim Paula II",
        "Jardim Paula II (2ª parte)",
        "Jardim Paula III",
        "Jardim Petrópolis",
        "Jardim Potiguar",
        "Jardim Primavera",
        "Jardim Sol Nascente I",
        "Jardim Sol Nascente II",
        "Jardim União",
        "Jardim Vasconcelos",
        "Jardim Vila Rica",
        "Jardim Vitória Régia",
        "Jeane",
        "João Baracat",
        "Joaquim Agostinho Curvo",
        "Karla Renata",
        "Lagoa do Jacaré",
        "Liberdade",
        "Limpo Grande",
        "Lucimar Campos",
        "Manga",
        "Manto Verde",
        "Mapim",
        "Marajoara",
        "Márcia",
        "Marechal Rondon",
        "Margaridas",
        "Maria Izabel",
        "Maristela",
        "Miguel Lana",
        "Monte Castelo",
        "Morada dos Florais",
        "Nair Sacre",
        "Nancy",
        "New Iara",
        "Noíse Curvo",
        "Nossa Senhora da Guia",
        "Nossa Senhora de Santana",
        "Nova Esperança",
        "Nova Flórida",
        "Nova Fronteira",
        "Nova Ipê",
        "Nova Várzea Grande",
        "Novo Mundo",
        "Núcleo do Sesi",
        "Nucleo G",
        "Nucleo G Ampliação",
        "Núcleo III",
        "Ouro Verde",
        "Paço Real",
        "Pai André",
        "Paiaguás",
        "Pampulha",
        "Panamericano",
        "Pari",
        "Parque Ambar",
        "Parque Ambar II",
        "Parque Arco Íris",
        "Parque Bandeirantes",
        "Parque Boa Vista I",
        "Parque Boa Vista II",
        "Parque Bom Jardim",
        "Parque Centro Oeste",
        "Parque das Nações",
        "Parque Del Rey",
        "Parque do Ipê",
        "Parque do Lago",
        "Parque dos Pequizeiros",
        "Parque Industrial Atlântico",
        "Parque Inustrial San Marco",
        "Parque Mangabeiras",
        "Parque Nova Era",
        "Parque Ouro Branco",
        "Parque Paiaguas",
        "Parque Paiaguás",
        "Parque Residencial Cláudia",
        "Parque Sabiá",
        "Parque São João",
        "Parque Tamoyos",
        "Parque Tremendão",
        "Passagem da Conceição",
        "Paulo Leite",
        "Petrópolis",
        "Pirinéu",
        "Planalto Beira Rio",
        "Planalto Ipiranga",
        "Planalto Ipiranga II",
        "Poço Grande",
        "Ponce de Arruda",
        "Ponte Nova",
        "Ponte Velha",
        "Portal Amazonas",
        "Portal da Amazônia",
        "Porto Imperial",
        "Praia Grande",
        "Primavera",
        "Recreio do Pari",
        "Regina",
        "Renato José dos Santos",
        "Rio dos Peixes",
        "Rosa Imperial",
        "Sadia I",
        "Sadia III",
        "Santa Cecília",
        "Santa Clara",
        "Santa Fé",
        "Santa Izabel",
        "Santa Luzia",
        "Santa Maria I",
        "Santa Maria II",
        "Santa Mercedes",
        "Santa Rosa",
        "Santa Terezinha I",
        "Santa Terezinha II",
        "Santos Dumont",
        "São Francisco",
        "São Gonçalo",
        "São Jeronimo",
        "São João",
        "São Jorge",
        "São José",
        "São Marcos",
        "São Matheus",
        "São Sebastião",
        "São Simão",
        "Sayonara",
        "Serra Dourada",
        "Souza Lima",
        "Sumaré",
        "Tarumã",
        "Tatiana",
        "Terra Nova",
        "Uirapuru",
        "Umuarama",
        "Unipark",
        "Valo Verde",
        "Vereador Abelardo de Azevedo",
        "Vila Arthur",
        "Vila Ipase",
        "Vila Ipiranga",
        "Vila Maria",
        "Vila Operária",
        "Vila Rosimery",
        "Vila Sadia",
        "Vila Suiça",
        "Vila União",
        "Vila Vitoria",
        "Village Ouro Preto",
        "Vista Alegre",
        "Vitória Régia",
    ])
});
